Started logging messages at Sun Oct 06 16:18:15 2019
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 1 B-reps in file
Info:    Found 24 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 64
Info:            Created 
Info:        Working on 89
Info:            Created 
Info:        Working on 10
Info:            Created 
Info:        Working on 87
Info:            Created 
Info:        Working on 117
Info:            Created 
Info:        Working on 15
Info:            Created 
Info:        Working on 114
Info:            Created 
Info:        Working on 115
Info:            Created 
Info:        Working on 22
Info:            Created 
Info:        Working on 32
Info:            Created 
Info:        Working on 210
Info:            Created 
Info:        Working on 281
Info:            Created 
Info:        Working on 274
Info:            Created 
Info:        Working on 330
Info:            Created 
Info:        Working on 334
Info:            Created 
Info:        Working on 47
Info:            Created 
Info:        Working on 275
Info:            Created 
Info:        Working on 315
Info:            Created 
Info:        Working on 69
Info:            Created 
Info:        Working on 252
Info:            Created 
Info:        Working on 251
Info:            Created 
Info:        Working on 98
Info:            Created 
Info:        Working on 133
Info:            Created 
Info:        Working on 191
Info:            Created 
Info:        Working on 262
Info:            Created 
Info:        Working on 292
Info:            Created 
Info:        Working on 287
Info:            Created 
Info:        Working on 340
Info:            Created 
Info:        Working on 341
Info:            Created 
Info:        Working on 119
Info:            Created 
Info:        Working on 93
Info:            Created 
Info:        Working on 127
Info:            Created 
Info:        Working on 184
Info:            Created 
Info:        Working on 256
Info:            Created 
Info:        Working on 320
Info:            Created 
Info:        Working on 343
Info:            Created 
Info:        Working on 233
Info:            Created 
Info:        Working on 355
Info:            Created 
Info:        Working on 402
Info:            Created 
Info:        Working on 403
Info:            Created 
Info:        Working on 359
Info:            Created 
Info:        Working on 238
Info:            Created 
Info:        Working on 351
Info:            Created 
Info:        Working on 385
Info:            Created 
Info:        Working on 405
Info:            Created 
Info:        Working on 407
Info:            Created 
Info:        Working on 311
Info:            Created 
Info:        Working on 170
Info:            Created 
Info:        Working on 240
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 7.74113e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 0 found       0 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Sun Oct 06 16:18:16 2019
